name: LightFM build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
    contents: write
  
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [ "3.11" ]
    steps:
      - uses: actions/checkout@v6
      
      # - uses: actions/checkout@v6
      #   with:
      #     # Repository name with owner. For example, actions/checkout
      #     # Default: ${{ github.repository }}
      #     repository: 'lyst/lightfm'
      #     ref: '1.17'
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.9 # 3.1.46
          
      - run: |
          sudo apt-get update && \
          sudo apt-get install -y libxml2 libxslt-dev wget bzip2 gcc
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel==0.45.1 setuptools --upgrade
          pip install pyodide-build
          pyodide venv .venv-pyodide

      - working-directory: 'lightfm'
        run: |
          pyodide build && \
          ls -R

  # /home/runner/work/lightfm-pyodide/lightfm-pyodide/lightfm/dist/lightfm-1.17-cp311-cp311-emscripten_3_1_46_wasm32.whl

      # - name: Archive Release
      #   uses: thedoctor0/zip-release@master
      #   with:
      #     type: 'zip'
      #     path: ${{ github.event.repository.name }}*
      #     filename: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "lightfm/dist/*.whl"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

  #     - uses: fastai/workflows/ssh@master
  #       with:
  #         ssh_key: ${{ secrets.SSH_KEY }}
  #         key_file: id_ecdsa
  # #     - uses: actions/checkout@v2
  # #     - run: source script-linux.sh
  #     - name: Setup tmate session
  #       uses: mxschmitt/action-tmate@master
